import type { Metadata } from "next";
import localFont from "next/font/local";
import { Lora } from "next/font/google"; // Import Lora from Google Fonts

import "./globals.css";
import { ToastContainer } from "react-toastify";

// Load Lora from Google Fonts
const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-lora",
});

export const metadata: Metadata = {
  title: "WhatsApp Bot Manager",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${lora.variable} antialiased`}
        style={{ fontFamily: '"Poppins", "Arial", sans-serif' }} // Apply Poppins
      >
        <ToastContainer position="bottom-right" />
        {children}
      </body>
    </html>
  );
}
